const newGameData = {
  chal: 0,
  dicevalue : 0,
  person: [],
  close: false,
  sixcount: 0,
  price : 0,
  waitting : true,
  ranks : [],
  isdice : false,
  roll : false,
  0 : new Array(4).fill(-1),
  1 : new Array(4).fill(-1),
  2 : new Array(4).fill(-1),
  3 : new Array(4).fill(-1),
  persons : [0,1,2,3],
  start : false,
  givechal : false,
  isroom : false,
};
module.exports = newGameData;
